timbunce/devel-nytprof

bin/nytprofhtml

nytprof scripts may not be installed to the main Perl installation bin
(e.g. when using perlbrew locallibs). If the scripts don't exist in
$Config{bin} check the PATH, and if they still can't be found die.

fallback to checking PATH for nytprof scripts

---

t/test40pmc.t

from https://metacpan.org/source/CORION/parent-0.231/t/parent-pmc.t which recently got a PMC fix by me

PERL_DISABLE_PMC might be anywhere, not in CCFLAGS

---

FileHandle.xs

512(a disk sector)-8096(glibc) are typical amounts, go higher than that

use setvbuf to increase buffer size

---

Changes
NYTProf.xs
lib/Devel/NYTProf.pm

This patch fixes the issues in https://github.com/timbunce/devel-nytprof/issues/31 (I tested the new patch on VC 2003, VC 6 and Strawberry Perl/GCC). The QPC code in https://github.com/timbunce/devel-nytprof/pull/26 was never merged due to the 
```
The sum of the statement timings is 1.$% of the total time profiling. (Values sl
ightly over 100% can be due simply to cumulative timing errors, whereas larger v
alues can indicate a problem with the clock used.)
Summary: statements profiled 16 (=16-0), sum of time 0.000225s, profile spanned
0.000000s
```
problem. I think the easiest way to fix that is special case it, that if the gettimeofday duration of the NYTProf run is 0.0 after using QPC clock, just ignore that it is 0.0 and dont issue a warning, which is what I did in this patch. There …

Add QueryPerformanceCounter clock for Windows

---

FileHandle.xs
NYTProf.xs

The context fixes are required to compile under PERL_IMPLICIT_CONTEXT with HAS_ZLIB.

Context fixes

---

bin/nytprofhtml

Here are the commit messages for convenience.
We want to have "\xB5]s" in our output file (part of a regex) instead of the
bytestring \xB5\x5D\x73 - which gives us invalid UTF-8.
Fixes problems with dark desktop themes (light font on light background, barely
links).
Just sets the colors on the BODY element and trusts in inheritance.
Also, set the color of unvisited links - which will propbably be set by the
(dark) theme, too.

Patches for minor glitches in nytprofhtml

---

bin/nytprofhtml

Hi,
Sometimes one needs wider flame graphs, and flamegraph.pl already has --width.

Add --flamewidth to nytprofhtml

---

bin/nytprofhtml

When [Browser::Open](https://metacpan.org/pod/Browser::Open) is available and it opens a browser, it returns the result of `system()` ([source code](https://metacpan.org/source/CFRANKS/Browser-Open-0.04/lib/Browser/Open.pm#L72)), which is the exit code of the process. On success, the exit code is zero. We now check for this and return without trying to open the browser again.
Previously, the browser was opening twice when the `--open` flag was provided.

Fix for the double opening of the web browser

---

t/lib/NYTProfTest.pm

Perl 5.26+ removes '.' from the default `@INC`, and this breaks the
mechanism internally where `@INC`-prefixes are stripped from fid_fileinfo
names ( in ::FileInfo.pm ).
This breaks tests due to the sample 'rdt' files expecting single-token
comparators relative to 't/', instead getting a fully qualified path in
the "got" side of the test.
This remedies this by ensuring a fully-qualified path to "t/" is in
`@INC` for the aforementioned prefix-stripper to pick-up on.
Closes: https://github.com/timbunce/devel-nytprof/issues/108
Bug: https://bugs.gentoo.org/615734

Fix test failures on Perl 5.26 w/ PERL_USE_UNSAFE_INC=0

---

NYTProf.xs

In incr_sub_inclusive_time, the write to subr_call_key could in some
circumstances write beyond the size of the buffer:
*** buffer overflow detected ***: /usr/sbin/uwsgi terminated
======= Backtrace: =========
/lib64/libc.so.6(__fortify_fail+0x37)[0x7fb2c7589d87]
/lib64/libc.so.6(+0x10df40)[0x7fb2c7587f40]
/lib64/libc.so.6(+0x10d449)[0x7fb2c7587449]
/lib64/libc.so.6(_IO_default_xsputn+0xbc)[0x7fb2c74f264c]
/lib64/libc.so.6(_IO_vfprintf+0x151d)[0x7fb2c74c269d]
/lib64/libc.so.6(__vsprintf_chk+0x88)[0x7fb2c75874d8]
/lib64/libc.so.6(__sprintf_chk+0x7d)[0x7fb2c758742d]
/usr/local/git_tree/main/lib/site/lib/auto/Devel/NYTProf/NYTProf.so(+0xe483)[0x7fb2ad9f0483]
/usr/local/booking-perl/5.24.3/lib/CORE/libperl.so(Perl_leave_scope+0x116)[0x7fb2c54fc3b6]
With gdb attached I could find the function: …

NYTProf.xs: prevent memory corruption in incr_sub_inclusive_time

---

bin/nytprofhtml

All numbers ending `5s` was handled as in µs. Actually, anything containing `\s`, `xs`, `Bs` or `5s` was handled as a time in µs.

Fix sorting of numbers ending ...5s as microsec

---

NYTProf.xs

Encountered a strange error in production, turns out it was related to NYTP_MAX_SUB_NAME_LEN, but it took a while to find the cause. Having 'NYTProf' in the 'buffer overflow' message would've helped a bit :)

Add 'NYTProf' to error output for easier triage

---

t/40-savesrc.t
t/lib/NYTProfTest.pm

Strawberry perl portable versions return different eval IDs,
presumably due to some eval calls prior to the profile start.
For example, '(eval 5)[-:1]' is returned instead of '(eval 1)[-:1]'.
The changes in this PR update the tests to identify when this happens, 
and then correct for it.
Has no effect on non-portable perls. 
Updates #76 and #94

Update test expectations for strawberry perl portable

---

.gitignore

Files matching these 3 patterns may be created in the course of running
individual test files through 'prove'.

3 entries for .gitignore

---

Makefile.PL
t/lib/NYTProfTest.pm

Purpose of this pull request is to provide the developer a short-cut to running a full `make test`.

Make test short 20210408

---

FileHandle.h
FileHandle.xs
Makefile.PL
NYTProf.xs
t/68-hashline.t
t/72-autodie.t

The purpose of this pull request is to pick some low-hanging fruit from [a larger p.r.](https://github.com/timbunce/devel-nytprof/pull/134) submitted in 2019 by @rurban.
3 of the commits are straightforward cherry-picks; 2 required slight corrections or adaptations.
I hope to work through the balance of the 44 commits and incorporate them into thematically grouped pull requests.
Thank you very much.
Jim Keenan

Selective cperl core cherries 20210408

---

NYTProf.xs
ppport.h

This pull request partially addresses the problem described in https://github.com/timbunce/devel-nytprof/issues/145.  It cherry-picks two commits submitted by @rurban in 2019 as part of https://github.com/timbunce/devel-nytprof/pull/134.
My local experimentation suggests that these commits eliminate all warnings but one that are generated during `make` when both `perl` and Devel::NYTProf are compiled with recent versions of `clang`, such as version 9 or 10.
Since those warnings are *not* generated during `make` when `perl` and Devel::NYTProf are compiled with recent `gcc`, the patches don't change anything in that case.
When, however, I compiled `perl` with a recent version of `g++` and then tried to install Devel::NYTProf, I found that the build processed failed with one of the module's …

Build time warnings 20210409

---

Makefile.PL

For: https://github.com/timbunce/devel-nytprof/issues/139
Thanks to the late Kent Fredric.

Prefer $Config{cpprun} to $Config{cpp}

---

README.md
t/11-reader.t
t/12-data.t
t/13-fileinfo.t
t/14-subinfo.t

Originally reported by H Merijn Brand; cd. https://github.com/timbunce/devel-nytprof/issues/168#issuecomment-832696861
[My first branch was misnamed, so the first p.r. was misnamed as well.]

Skip 4 test files on quadmath (Linux) builds

---

FileHandle.xs
Makefile.PL
NYTProf.xs
README.md

and the undefined OP_SETSTATE warning.
Note that a dev. version 6.04_01 fails in the t/40-savesrc.t test
Signed-off-by: James E Keenan <jkeenan@cpan.org>

Fix -Wc++11-compat warnings

---

NYTProf.xs

I recently committed a change to blead perl changing the return type of the SSNEW*() macros to SSize_t, since the I32 would overflow well before the scope stack index itself.
This change adapts Devel::NYTProf to store the full offset.  I expect this to make no difference to older perls, as SSPTR() is a simple macro adding the supplied offset to the scope stack base pointer.

support SSNEW*() macros returning SSize_t instead of I32

---

MANIFEST.SKIP
README.md

For: https://github.com/timbunce/devel-nytprof/issues/201

Remove reference to .travis-ci.org

---

t/test16.t

'given' and 'when' were deprecated during the 5.37 development cycle (committed Feb 25 2023).  So the last perl production release for which we should test then was 5.36; skip thereafter.

Don't test given/when once deprecated

---

bin/nytprofhtml

While investigating the profiling output on a project I'm working on I happened to notice that the link to Brendan Gregg's Flame Graph page was broken.  It seems that the new page is now on www.brendangregg.com (as implemented in this change).
The last snapshot on the internet archive to still point to the dtrace.org address is from November 2013:
https://web.archive.org/web/20131110195734/http://dtrace.org/blogs/brendan/2011/12/16/flame-graphs/ and the following snapshot in January 2014 points to the new address https://web.archive.org/web/20140121022436/http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html, which then seems to have morphed into the link I've used here.  Thus, I'm fairly sure that the link I've used to fix the broken one is correct.
This PR is submitted in the hope …

Update link to Flame Graph info in nytprofhtml output
